"""auto add phone number column in users table from base

Revision ID: 643975186d84
Revises: 49ac31259e99
Create Date: 2022-01-26 23:08:44.394002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643975186d84'
down_revision = '49ac31259e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
